plugins {
    id 'com.android.library'
}

android {
    namespace = 'm.co.rh.id.a_jarwis.base'
    compileSdk = 34

    buildFeatures {
        buildConfig = true

    }
    defaultConfig {
        minSdk = 21

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles = ['consumer-rules.pro']
        javaCompileOptions {
            annotationProcessorOptions {
                argument("room.schemaLocation", "$projectDir/schemas".toString())
            }
        }
    }

    buildTypes {
        debug{
            buildConfigField 'boolean', 'DEBUG', "true"
        }
        release {
            buildConfigField 'boolean', 'DEBUG', "false"
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    api libs.a.provider
    api libs.a.navigator
    api libs.a.navigator.dialog
    api libs.a.logger
    api libs.rx.utils
    api libs.rxandroid
    api libs.rxjava
    api libs.work.runtime
    api libs.androidx.appcompat
    api libs.material
    api libs.androidx.constraintlayout
    api libs.androidx.drawerlayout
    api libs.androidx.swiperefreshlayout
    api libs.androidx.recyclerview
    api libs.androidx.exifinterface
    api libs.room.runtime
    annotationProcessor libs.room.compiler

    implementation libs.concurrent.utils
    implementation libs.leakcanary.plumber

    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.mockito.core
}